routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/pickerspoint/addpp', 'PickersPointController@addpp')->name( 'pickerspoint.addpp');
Route::resource('pickerspoint', 'PickersPointController');


Route::get('/messages/compose', 'NotificationsController@compose')->name('messages.compose');

Route::get('/notifications/all', 'NotificationsController@notifications')->name('notifications.all');
Route::get('/notifications/mark_as_read', 'NotificationsController@mark_as_read')->name('notifications.mark_as_read');

Route::get('/', 'ViewController@index')->name('home');

Route::get('/profile/pickerspoint/{profile}', 'ProfileController@pickerspoint')->name('profile.pickerspoint');

Route::get('/profile/cashout', 'ProfileController@cashout')->name('profile.cashout');

Route::get('/profile/add_balance', 'ProfileController@add_balance')->name('profile.add_balance');

Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::get('/profile/create', 'ProfileController@create')->name('profile.create');

Route::post('/profile', 'ProfileController@store')->name( 'profile.store');

Route::get( '/profile/chefdishes/{profile}', 'ProfileController@chefdishes')->name('profile.chefdishes');

Route::post( '/profile/{profile}/isAvailable', 'ProfileController@isAvailable')->name('profile.isAvailable');

Route::get( '/profile/{user}/chefdelivery', 'ProfileController@chefdelivery')->name('profile.chefdelivery');

Route::get('/profile/{profile}', 'ProfileController@show')->name('profile.show');

Route::get('/profile/{profile}/edit', 'ProfileController@edit')->name('profile.edit');

Route::put( '/profile/{profile}', 'ProfileController@update')->name('profile.update');


Route::get( '/search/dsp', 'SearchController@dsp')->name( 'search.dsp');
Route::get( '/search/pp', 'SearchController@pp')->name( 'search.pp');

Route::get( '/search/livedish', 'SearchController@livedish')->name( 'search.livedish');
Route::post( '/search/livedish', 'SearchController@search_livedish')->name( 'search.livedish');


Route::get( '/delivery/AddService', 'DeliveryServiceController@create')->name( 'delivery.create');
Route::post( '/delivery/AddService', 'DeliveryServiceController@AddService')->name( 'delivery.AddService');

Auth::routes();

Route::get( '/dishes/manage', 'DishesController@manage')->name( 'dishes.manage');
Route::get( '/dishes/editdish', 'DishesController@editdish')->name( 'dishes.editdish');

Route::resource( '/dishes', 'DishesController');

Route::get('/ajax-subcat', 'RestApiController@jsonSubCat');
Route::get('/api/categories', 'RestApiController@jsonCategories');
Route::get('/ajax-areas', 'RestApiController@jsonAreas')->name('api.areas');
Route::get('/api/search-dish', 'RestApiController@jsonSearchDish')->name( 'api.search.dish');
Route::get('/api/search-dsp', 'RestApiController@jsonSearchDsp')->name( 'api.search.dsp');
Route::get('/api/search-pp', 'RestApiController@jsonSearchPP')->name( 'api.search.pp');
Route::get('/api/order/update', 'RestApiController@orderUpdate')->name( 'api.order.update');
Route::get('/api/order/load', 'RestApiController@orderLoad')->name( 'api.order.load');
Route::get('/api/dsp/getIDS', 'RestApiController@getIDs')->name( 'api.dsp.getIDs');

Route::get('/rating/{order}', 'RatingController@store')->name( 'rating.store');

Route::get('recover-pass', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('recover-pass');

Route::get('/home', 'HomeController@index');


// Auth Required Routes
Route::group(['middleware' => 'auth'], function (){
	// Order Routes
    Route::get( '/order/purchase', 'OrderController@purchase')->name( 'order.purchase');
    Route::get( '/order/selectdsp/{dish}', 'OrderController@selectdsp')->name( 'order.selectdsp');
    Route::get( '/order/confirm/{dsp}/{dish}', 'OrderController@confirm')->name( 'order.confirm');
    Route::get( '/order/confirm_pp/{pp}/{dish}', 'OrderController@confirm_pp')->name( 'order.confirm_pp');
    Route::get( '/order/store', 'OrderController@storeOrder')->name( 'order.store');
    Route::get( '/order/status/{order}', 'OrderController@status')->name( 'order.status');

	//Notifications
	Route::get('api/all_notifications', 'RestApiController@allNotification')->name( 'api.all_notifications');

	//Meassage
    Route::get('/messages/all', 'NotificationsController@messages')->name('messages.all');
    Route::get( '/messages/getMessages', 'MessageController@getMessages')->name( 'messages.getMessages');
	Route::get( '/messages/getAllMessages', 'MessageController@getAllMessages')->name( 'messages.getAllMessages');
	Route::get( '/messages/getSingleMessages', 'MessageController@getSingleMessages')->name( 'messages.getSingleMessages');
	Route::post( '/messages/store_with_auth', 'MessageController@store_with_auth')->name( 'messages.store_with_auth');
	Route::resource('messages', 'MessageController');

	// Payments
//    Route::post( 'admin/payment/add_balance', 'PaymentController@add_balance')->name( 'admin.payment.add_balance');
    Route::post( '/payment/add_balance', 'PaymentController@add_balance')->name( 'payment.add_balance');
    Route::post( '/payment/withdraw', 'PaymentController@withdraw')->name( 'payment.withdraw');

    //email to admin
    Route::post( '/order/complain', 'OrderController@complain')->name( 'order.complain');
});



Route::get('command/storage_link', function () {
    $exitCode = Artisan::call('storage:link');
    echo $exitCode;
    //
});

Route::get('command/migrate_fresh', function () {
    $exitCode = Artisan::call('migrate:fresh');
    echo $exitCode;
    //
});

Route::get('command/reset_order/{id}', function ($id) {
    $order = \App\Order::find($id);
    $order->chef_order_approved = 0;
    $order->chef_is_dish_ready = 0;
    $order->chef_is_dish_delivered = 0;
    $order->dsp_is_dish_recieved = 0;
    $order->dsp_is_dish_delivered = 0;
    $order->is_order_completed = 0;
    $order->status = 1;
    $order->created_at = \Carbon\Carbon::now();
    $order->save();

    return redirect()->back();

})->name('command.reset_order');

app/Http/Controllers/DishesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\DeliveryService;
use App\Dish;

use App\PickersPoint;
use App\Profile;
use App\User;
use App\Rating;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Storage;


class DishesController extends Controller
{

	public function __construct() {
		$this->middleware('auth')->except('show');
	}

	public function index()
    {
        //
    }

    public function create()
    {
        $user = auth()->user();
        if(!$user->profile->address || !$user->profile->mobile_no || !$user->profile->city) {
            return redirect()->route('profile.edit', ['profile' => $user->profile->id])->withErrors('You Must Fill Up The Profile Information To Create a New Dish');
        }

		$categories = new Category;
		$categories = $categories->get();
        $dsp_ids = DeliveryService::select('id', 'service_title')
            ->whereHas('profile', function ($query) {
                $query->where('city', '=', auth()->user()->profile->city);
            })
            ->get();
        $pp_ids = PickersPoint::select('id', 'name')
            ->whereHas('profile', function ($query) {
                $query->where('city', '=', auth()->user()->profile->city);
            })
            ->get();

//        return $dsp_ids;

	    return view('dishes.create', compact( 'categories', 'dsp_ids', 'pp_ids'));
    }

    public function store(Request $request)
    {
        $user = auth()->user();
        if(!$user->profile->address || !$user->profile->mobile_no || !$user->profile->city) {
            return redirect()->route('profile.edit', ['profile' => $user->profile->id])->withErrors('You Must Fill Up The Profile Information To Create a New Dish');
        }

        $validatedData = $request->validate([
            'dish_category' => 'required|string|max:50',
            'dish_subcategory' => 'required|string|max:50',
            'preparation_time' => 'required|integer|min:1|max:4',
            'dish_name' => 'required|string|max:50|min:3',
            'dish_price' => 'required|integer|min:10|max:9999',
            'dish_description' => 'required|max:5000|string|min:2',
            'dsp_1' => 'nullable|integer|min:1',
            'dsp_2' => 'nullable|integer|min:1',
            'dsp_3' => 'nullable|integer|min:1',
            'pp1' => 'nullable|integer|min:1',
            'pp2' => 'nullable|integer|min:1',
            'pp3' => 'nullable|integer|min:1',
            'dish_thumbnail' => 'required|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_1' => 'required|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_2' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_3' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'avg_rating' => 'nullable',
            'is_approved' => 'nullable|boolean',

        ]);

        if(!$request->input('dsp_1') && !$request->input('dsp_2')
            && !$request->input('dsp_3') && !$request->input('pp1')
            && !$request->input('pp2') && !$request->input('pp3')
        ) {
            return redirect()->back()->withInput()->withErrors(['Error', 'Please Input at least one dsp or pickerspoint id']);
        } /*else {
            return redirect()->back()->with('success', 'You have Inputed at least one dsp or pickerspoint id');
        }*/

	    $id = auth()->id();
	    $profile = Profile::where('user_id', $id)->first();

	    $dish = new Dish;
	    $dish->profile_id = $profile->id;
	    $dish->dish_category = Input::get('dish_category');
	    $dish->dish_subcategory = Input::get('dish_subcategory');
	    $dish->preparation_time = Input::get('preparation_time');
	    $dish->dish_name = $request->input('dish_name');
	    $dish->dish_price = $request->input('dish_price');
	    $dish->dish_description = $request->input('dish_description');
//	    $dish->item_tags = $request->input('item_tags');
	    $dish->dsp_1 = $request->input('dsp_1');
	    $dish->dsp_2 = $request->input('dsp_2');
	    $dish->dsp_3 = $request->input('dsp_3');
	    $dish->pp1 = $request->input('pp1');
	    $dish->pp2 = $request->input('pp2');
	    $dish->pp3 = $request->input('pp3');

	    $this->upload_image( $request, $dish, 'dish_images', 'dish_thumbnail', false);
	    $this->upload_image( $request, $dish, 'dish_images', 'dish_image_1', false);
	    $this->upload_image( $request, $dish, 'dish_images', 'dish_image_2', false);
	    $this->upload_image( $request, $dish, 'dish_images', 'dish_image_3', false);

	    $dish->save();
//	    session()->flash('success', 'Dish has been created successfully');
//        $request->session()->flash();

        return redirect()->route( 'profile.show', [ 'profile' => $profile ])->with('success', 'Dish has been created successfully');
    }

    public function show($id)
    {
	    $dish = Dish::find($id);
	    $profile = $dish->profile;

	    $ratings = Rating::where('chef_id', $profile->id)->where('dish_id', $dish->id)->get();

	    $avg_rating = 0;
	    $rating_sum = 0;
	    $i = 0;

	    foreach ($ratings as $rating) {
	    	$rating_sum += $rating->rating;
	    	$i++;
	    }

	    if($i != 0) {
			$avg_rating = $rating_sum / $i;
	    }
	    
	    // echo "avg_Rating: " . $avg_rating . "<br>";

	    $half_star = false;

    	$rounded_avg_rating = round($avg_rating);
    	if(abs($rounded_avg_rating - $avg_rating) >= .25 ) {
    		$half_star = true;
    	}

    	if($half_star) {
    		if(($avg_rating - $rounded_avg_rating) < 0) {
    			$avg_rating = $rounded_avg_rating - 1;
    		} else {
    			$avg_rating = $rounded_avg_rating;
    		}
    		
    	} else {
    		$avg_rating = $rounded_avg_rating;
    	}
	   

	    /*echo "avg_Rating: " . $avg_rating . "<br>";
	    echo "rounded_avg_rating: " . $rounded_avg_rating . "<br>";
	    echo "half_star: " . $half_star . "<br>";*/
	    

        return view('dishes.single-dish', compact( 'profile', 'dish', 'ratings', 'avg_rating', 'half_star'));
    }

    public function edit($id)
    {
    	$dish = Dish::find($id);
    	if($dish->profile_id != auth()->user()->profile->id) {
    	    return redirect()->back()->withErrors('You are not authorized to edit this dish');
        }
        $categories = new Category;
        $categories = $categories->get();
        $dsp_ids = DeliveryService::select('id', 'service_title')
            ->whereHas('profile', function ($query) {
                $query->where('city', '=', auth()->user()->profile->city);
            })
            ->get();
        $pp_ids = PickersPoint::select('id', 'name')
            ->whereHas('profile', function ($query) {
                $query->where('city', '=', auth()->user()->profile->city);
            })
            ->get();

//        return $dsp_ids;

	    return view('dishes.dish-edit', compact( 'dish', 'categories', 'dsp_ids', 'pp_ids'));
    }

    public function update(Request $request, $id)
    {
        ini_set('max_execution_time', 300);
        ini_set('memory_limit','2048M');

        $validatedData = $request->validate([
            'dish_category' => 'string|max:50',
            'dish_subcategory' => 'string|max:50',
            'preparation_time' => 'integer|min:1|max:4',
            'dish_name' => 'string|max:50|min:3',
            'dish_price' => 'integer|min:10|max:9999',
            'dish_description' => 'max:5000|string|min:2',
            'dsp_1' => 'nullable|integer|min:1',
            'dsp_2' => 'nullable|integer|min:1',
            'dsp_3' => 'nullable|integer|min:1',
            'pp1' => 'nullable|integer|min:1',
            'pp2' => 'nullable|integer|min:1',
            'pp3' => 'nullable|integer|min:1',
            /*'dish_thumbnail' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_1' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_2' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',
            'dish_image_3' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg,bmp|max:5120',*/
            'avg_rating' => 'nullable',
            'is_approved' => 'nullable|boolean',

        ]);

        $dish = Dish::find($id);
	    $profile = $dish->profile;

        if($dish->profile_id != auth()->user()->profile->id) {
            return redirect()->back()->withErrors('You are not authorized to edit this dish');
        }

	    if (request()->filled('dish_category')) {
		    $dish->dish_category = $request->input('dish_category');
	    }
	    if (request()->filled('dish_subcategory')) {
		    $dish->dish_subcategory = $request->input('dish_subcategory');
	    }
	    if (request()->filled('preparation_time')) {
		    $dish->preparation_time = $request->input('preparation_time');
	    }
	    if (request()->filled('dish_name')) {
		    $dish->dish_name = $request->input('dish_name');
	    }
    	if (request()->filled('dish_price')) {
		    $dish->dish_price = $request->input('dish_price');
	    }
    	if (request()->filled('dish_description')) {
		    $dish->dish_description = $request->input('dish_description');
	    }

        if (request()->filled('dsp_1')) {
            $dish->dsp_1 = $request->input('dsp_1');
        }

        if (request()->filled('dsp_2')) {
            $dish->dsp_2 = $request->input('dsp_2');
        }

        if (request()->filled('dsp_3')) {
            $dish->dsp_3 = $request->input('dsp_3');
        }

	    if (request()->filled('pp1')) {
            $dish->pp1 = $request->input('pp1');
        }

	    if (request()->filled('pp2')) {
            $dish->pp2 = $request->input('pp2');
        }

	    if (request()->filled('pp3')) {
            $dish->pp3 = $request->input('pp3');
        }

	    if($request->hasFile('dish_thumbnail')) {
            $this->upload_image( $request, $dish, 'dish_images', 'dish_thumbnail', true);
        }

        if($request->hasFile('dish_image_1')) {

resources/views/dishes/box_dish_preview.blade.php
<div class="product product--card">
    <div class="product__thumbnail">
        <div class="aspect_ratio"> <img src="{{ route('home') }}/storage/images/dish_images/{{ $dish->dish_thumbnail }}" alt="Product Image" class="ratio_img"> </div>
        <div class="prod_btn">
            <a href="{{ route('dishes.show', ['id' => $dish]) }}" class="transparent btn--sm btn--round">MoreInfo</a>
        </div>
        <!-- end /.prod_btn -->
    </div>
    <!-- end /.product__thumbnail -->
    <div class="product-desc">
        <a href="{{ route('dishes.show', ['id' => $dish]) }}" class="product_title">
            <h4> {{ $dish->dish_name }} </h4> </a>
        <ul class="titlebtm">
            <li> <img class="auth-img" src="{{ route('home') }}/storage/images/profile_image/{{ $dish->profile->profile_image }}" alt="author image">
                <p> <a href="{{ route('profile.show', ['profile' => $dish->profile->id]) }} #profile">{{ $dish->profile->user->name }}</a> </p>
            </li>
            <li class="product_cat a-color">
                <span class="lnr lnr-map-marker"></span><span>{{ $dish->profile->city }},</span><span>{{ $dish->profile->area }}</span></li>
        </ul>
    </div>
    <!-- end /.product-desc -->
    <div class="product-purchase">
        <div class="price_love"> <span>৳{{ $dish->dish_price }}</span>

            <div class="rating product--rating pull-right">
                <ul>
                    @for ($i=1; $i <= 5; $i++)

                        <li>
                            @if($i <= round($dish->avg_rating))
                                <span class="fa fa-star"></span>
                            @else
                                <span class="fa fa-star-o"></span>
                            @endif
                        </li>

                    @endfor
                </ul>
            </div>

        </div>

        <div class="sell">
            <p>
                        <span data-toggle="tooltip" data-placement="bottom" title="Total Dish Sale">
                      <i class="fa fa-paper-plane-o" style="color:#f64646" aria-hidden="true"></i>
                      <span>{{ count($dish->completed_orders) }}</span></span>
            </p>
        </div>
    </div>
    <!-- end /.product-purchase -->
</div>

resources/views/dishes/index.blade.php
@extends ('layouts.master')

@section ('title', 'Sale or Eat homemade foods from anywhere')

@section ('content')



@endsection

resources/views/dishes/manage-dish.blade.php
@extends ('layouts.master')

@section ('title', 'Manage your dishes Edit and Delete')


@section ('content')

  <!--================================
        START BREADCRUMB AREA
    =================================-->
  <section class="breadcrumb-area">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-title">Manage your dishes</h1>
        </div>
        <!-- end /.col-md-12 -->
      </div>
      <!-- end /.row -->
    </div>
    <!-- end /.container -->
  </section>
  <!--================================
      END BREADCRUMB AREA
  =================================-->

  <!--================================
          START DASHBOARD AREA
  =================================-->
  <section class="dashboard-edit dashboard-area">
    @include('includes.menu-dashboard')
    <div class="dashboard_contents">
      <div class="container">
        <div class="row s-hide">
          <div class="col-md-12">
            <div class="filter-bar dashboard_title_area clearfix filter-bar2">
              <div class="dashboard__title dashboard__title pull-left">
                <h3>Manage Dish</h3>
              </div>

              <div class="pull-right">
                <div class="filter__option filter--text">
                  <p>
                    <span>Total Dish: {{ count($dishes) }}</span></p>
                </div>

                <div class="filter__option filter--select">
                  <div class="select-wrap">
                    <select name="price">
                      <option value="low">Price : Low to High</option>
                      <option value="high">Price : High to low</option>
                    </select>
                    <span class="lnr lnr-chevron-down"></span>
                  </div>
                </div>
              </div>
              <!-- end /.pull-right -->
            </div>
            <!-- end /.filter-bar -->
          </div>
          <!-- end /.col-md-12 -->
        </div>
        <!-- end /.row -->

        <div class="row">

        @foreach($dishes as $dish)
          <!-- start .col-md-4 -->
            <div class="col-lg-4 col-md-6">
              <!-- start .single-product -->
              <div class="product product--card">

                <div class="product__thumbnail">
                  <div class="aspect_ratio">
                    <img src="{{ route('home') }}/storage/images/dish_images/{{ $dish->dish_thumbnail }}"
                         alt="Product Image" class="ratio_img">
                  </div>

                  <div class="prod_option">
                    <a href="#" id="drop2" class="dropdown-trigger" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="true">
                      <span class="lnr lnr-cog setting-icon"></span>
                    </a>

                    <div class="options dropdown-menu" aria-labelledby="drop2">
                      <ul>
                        <li>
                          <a href="{{ route('dishes.edit', ['id' => $dish]) }}">
                            <span class="lnr lnr-pencil"></span>Edit
                          </a>
                        </li>
                        <li>
                          <a href="#" data-toggle="modal" data-target="#myModal2"
                             class="delete">
                            <span class="lnr lnr-trash"></span>Delete
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <!-- end /.product__thumbnail -->

                <div class="product-desc">
                  <a href="{{ route('dishes.show', ['id' => $dish]) }}" class="product_title">
                    <h4>{{ $dish->dish_name }}</h4>
                  </a>
                  <ul class="titlebtm">
                    <li>
                      <img class="auth-img"
                           src="{{ route('home') }}/storage/images/profile_image/{{ $profile->profile_image }}"
                           alt="Profile image">
                      <p>
                        <a href="{{ route('profile.show', ['profile' => $profile]) }}">{{ $profile->fullname }}</a>
                      </p>
                    </li>
                    <li class="product_cat">
                      <a href="#">From
                        <span> Sylhet</span></a>
                    </li>
                  </ul>
                </div>
                <!-- end /.product-desc -->

                <div class="product-purchase">
                  <div class="price_love">
                    <span>৳{{ $dish->dish_price }}</span>

                  </div>

                  <div class="rating product--rating">
                    <ul>
                      @for ($i=1; $i <= 5; $i++)

                        <li>
                          @if($i <= round($dish->avg_rating))
                            <span class="fa fa-star"></span>
                          @else
                            <span class="fa fa-star-o"></span>
                          @endif
                        </li>

                      @endfor
                    </ul>
                  </div>

                  <div class="sell">
                    <p>
                      <span data-toggle="tooltip" data-placement="bottom" title="Total Dish Sale">
                      <i class="fa fa-paper-plane-o" style="color:#f64646" aria-hidden="true"></i>
                      <span>{{ count($dish->completed_orders) }}</span></span>
                    </p>
                  </div>
                </div>
                <!-- end /.product-purchase -->
              </div>
              <!-- end /.single-product -->
            </div>
            <!-- end /.col-md-4 -->
            <div class="modal fade rating_modal item_remove_modal" id="myModal2" tabindex="-1" role="dialog"
                 aria-labelledby="myModal2">
              <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h3 class="modal-title">Are you sure to delete this item?</h3>
                    <p>You will not be able to recover this file!</p>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <!-- end /.modal-header -->

                  <div class="modal-body">
                    <form action="{{ route('dishes.destroy', ['id' => $dish]) }}" method="post">
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn--round btn-danger btn--default">Delete</button>
                      <button class="btn btn--round modal_close" data-dismiss="modal">Cancel</button>
                    </form>

                  </div>
                  <!-- end /.modal-body -->
                </div>
              </div>
            </div>
          @endforeach

        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="text-center">
              {{--<nav class="navigation pagination" role="navigation">
                <div class="nav-links">
                  <a class="prev page-numbers" href="#">
                    <span class="lnr lnr-arrow-left"></span>
                  </a>
                  <a class="page-numbers current" href="#">1</a>
                  <a class="page-numbers" href="#">2</a>
                  <a class="page-numbers" href="#">3</a>
                  <a class="next page-numbers" href="#">
                    <span class="lnr lnr-arrow-right"></span>
                  </a>
                </div>
              </nav>--}}
              {{ $dishes->links() }}
            </div>
            <!-- end /.pagination-area -->
          </div>
          <!-- end /.col-md-12 -->
        </div>
        <!-- end /.row -->
      </div>
      <!-- end /.container -->
    </div>
    <!-- end /.dashboard_menu_area -->
  </section>
  <!--================================
          END DASHBOARD AREA
  =================================-->

@endsection