routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/pickerspoint/addpp', 'PickersPointController@addpp')->name( 'pickerspoint.addpp');
Route::resource('pickerspoint', 'PickersPointController');


Route::get('/messages/compose', 'NotificationsController@compose')->name('messages.compose');

Route::get('/notifications/all', 'NotificationsController@notifications')->name('notifications.all');
Route::get('/notifications/mark_as_read', 'NotificationsController@mark_as_read')->name('notifications.mark_as_read');

Route::get('/', 'ViewController@index')->name('home');

Route::get('/profile/pickerspoint/{profile}', 'ProfileController@pickerspoint')->name('profile.pickerspoint');

Route::get('/profile/cashout', 'ProfileController@cashout')->name('profile.cashout');

Route::get('/profile/add_balance', 'ProfileController@add_balance')->name('profile.add_balance');

Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::get('/profile/create', 'ProfileController@create')->name('profile.create');

Route::post('/profile', 'ProfileController@store')->name( 'profile.store');

Route::get( '/profile/chefdishes/{profile}', 'ProfileController@chefdishes')->name('profile.chefdishes');

Route::post( '/profile/{profile}/isAvailable', 'ProfileController@isAvailable')->name('profile.isAvailable');

Route::get( '/profile/{user}/chefdelivery', 'ProfileController@chefdelivery')->name('profile.chefdelivery');

Route::get('/profile/{profile}', 'ProfileController@show')->name('profile.show');

Route::get('/profile/{profile}/edit', 'ProfileController@edit')->name('profile.edit');

Route::put( '/profile/{profile}', 'ProfileController@update')->name('profile.update');


Route::get( '/search/dsp', 'SearchController@dsp')->name( 'search.dsp');
Route::get( '/search/pp', 'SearchController@pp')->name( 'search.pp');

Route::get( '/search/livedish', 'SearchController@livedish')->name( 'search.livedish');
Route::post( '/search/livedish', 'SearchController@search_livedish')->name( 'search.livedish');


Route::get( '/delivery/AddService', 'DeliveryServiceController@create')->name( 'delivery.create');
Route::post( '/delivery/AddService', 'DeliveryServiceController@AddService')->name( 'delivery.AddService');

Auth::routes();

Route::get( '/dishes/manage', 'DishesController@manage')->name( 'dishes.manage');
Route::get( '/dishes/editdish', 'DishesController@editdish')->name( 'dishes.editdish');

Route::resource( '/dishes', 'DishesController');

Route::get('/ajax-subcat', 'RestApiController@jsonSubCat');
Route::get('/api/categories', 'RestApiController@jsonCategories');
Route::get('/ajax-areas', 'RestApiController@jsonAreas')->name('api.areas');
Route::get('/api/search-dish', 'RestApiController@jsonSearchDish')->name( 'api.search.dish');
Route::get('/api/search-dsp', 'RestApiController@jsonSearchDsp')->name( 'api.search.dsp');
Route::get('/api/search-pp', 'RestApiController@jsonSearchPP')->name( 'api.search.pp');
Route::get('/api/order/update', 'RestApiController@orderUpdate')->name( 'api.order.update');
Route::get('/api/order/load', 'RestApiController@orderLoad')->name( 'api.order.load');
Route::get('/api/dsp/getIDS', 'RestApiController@getIDs')->name( 'api.dsp.getIDs');

Route::get('/rating/{order}', 'RatingController@store')->name( 'rating.store');

Route::get('recover-pass', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('recover-pass');

Route::get('/home', 'HomeController@index');


// Auth Required Routes
Route::group(['middleware' => 'auth'], function (){
	// Order Routes
    Route::get( '/order/purchase', 'OrderController@purchase')->name( 'order.purchase');
    Route::get( '/order/selectdsp/{dish}', 'OrderController@selectdsp')->name( 'order.selectdsp');
    Route::get( '/order/confirm/{dsp}/{dish}', 'OrderController@confirm')->name( 'order.confirm');
    Route::get( '/order/confirm_pp/{pp}/{dish}', 'OrderController@confirm_pp')->name( 'order.confirm_pp');
    Route::get( '/order/store', 'OrderController@storeOrder')->name( 'order.store');
    Route::get( '/order/status/{order}', 'OrderController@status')->name( 'order.status');

	//Notifications
	Route::get('api/all_notifications', 'RestApiController@allNotification')->name( 'api.all_notifications');

	//Meassage
    Route::get('/messages/all', 'NotificationsController@messages')->name('messages.all');
    Route::get( '/messages/getMessages', 'MessageController@getMessages')->name( 'messages.getMessages');
	Route::get( '/messages/getAllMessages', 'MessageController@getAllMessages')->name( 'messages.getAllMessages');
	Route::get( '/messages/getSingleMessages', 'MessageController@getSingleMessages')->name( 'messages.getSingleMessages');
	Route::post( '/messages/store_with_auth', 'MessageController@store_with_auth')->name( 'messages.store_with_auth');
	Route::resource('messages', 'MessageController');

	// Payments
//    Route::post( 'admin/payment/add_balance', 'PaymentController@add_balance')->name( 'admin.payment.add_balance');
    Route::post( '/payment/add_balance', 'PaymentController@add_balance')->name( 'payment.add_balance');
    Route::post( '/payment/withdraw', 'PaymentController@withdraw')->name( 'payment.withdraw');

    //email to admin
    Route::post( '/order/complain', 'OrderController@complain')->name( 'order.complain');
});



Route::get('command/storage_link', function () {
    $exitCode = Artisan::call('storage:link');
    echo $exitCode;
    //
});

Route::get('command/migrate_fresh', function () {
    $exitCode = Artisan::call('migrate:fresh');
    echo $exitCode;
    //
});

Route::get('command/reset_order/{id}', function ($id) {
    $order = \App\Order::find($id);
    $order->chef_order_approved = 0;
    $order->chef_is_dish_ready = 0;
    $order->chef_is_dish_delivered = 0;
    $order->dsp_is_dish_recieved = 0;
    $order->dsp_is_dish_delivered = 0;
    $order->is_order_completed = 0;
    $order->status = 1;
    $order->created_at = \Carbon\Carbon::now();
    $order->save();

    return redirect()->back();

})->name('command.reset_order');

resources/views/includes/author_info.blade.php
<div class="author-card sidebar-card">
    <div class="author-infos">
        <div class="author_avatar"> <img src="{{ route('home') }}/storage/images/profile_image/{{ $profile->profile_image }}" alt="Presenting the broken author avatar :D"> </div>
        <div class="author">
            <a href="{{ route('profile.show', ['profile' => $profile->id]) }} #profile"><h4>
                {{ $profile->user->name }}
            </h4></a>
            <p>Joined {{ $profile->created_at->toFormattedDateString() }}</p>
        </div>
        <div class="author-badges">
            <ul class="list-unstyled">
                @if($profile->user->isChef())
                <li> <span data-toggle="tooltip" data-placement="bottom" title="Have up to 10 dish for sale">
                        <img src="{{ URL::to('/') }}/images/svg/have_dish.png" alt="" class="svg">
                    </span> </li>
                @endif
                    @if($profile->user->isDsp())
                <li> <span data-toggle="tooltip" data-placement="bottom" title="Have delivery option">
                        <img src="{{ URL::to('/') }}/images/svg/delivery.png" alt="" class="svg">
                    </span> </li>
                    @endif
                    @if($profile->user->isPP())
                <li> <span data-toggle="tooltip" data-placement="bottom" title="Hosting his place for dish collection">
                        <img src="{{ URL::to('/') }}/images/svg/pcikerpoint.png" alt="" class="svg">
                    </span> </li>
                        @endif
            </ul>
        </div>
        <!-- end /.author -->
    </div>
    <!-- end /.author-infos -->
    <div class="freelance-status">
        <div class="author-badges">
            <div class="author-btn"> <button class="btn btn--md btn--round" data-toggle="modal" data-target="#messageModal"
                                             @if(auth()->id() == $profile->user_id)
                                             aria-disabled="true" disabled="disabled"

                        @endif
                >Message Chef</button> </div>
        </div>
    </div>
</div>

<!-- Modal for sending message -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="messageModalLabel">Message {{ $profile->user->name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form action="{{ route('messages.store_with_auth') }}" method="post" id="send_msg">
                    @csrf
                    <input type="hidden" name="sender_id" value="{{ auth()->id() }}">
                    <input type="hidden" name="recipient_id" value="{{ $profile->user->id }}">

                    <div class="form-group">
                        <label for="msgText">Type your message Below</label>
                        <textarea class="form-control" id="msgText" placeholder="I want to buy your dish" name="body"></textarea>
                    </div>

                    {{-- <button type="submit" id="submit-form" class="d-none">send</button> --}}

                </form>
            </div>

            <div class="modal-footer">
                {{-- <label for="submit-form" tabindex="0"  class="btn btn-primary px-3 py-1">Send</label> --}}
                <button type="button" class="btn btn-primary px-3 py-1" form="send_msg" id="submit-form">Send</button>

                <button type="button" class="btn btn-secondary px-3 py-1" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<div id="snackbar">Snackbar</div>

@push('scripts-footer-bottom')
<script type="text/javascript">
    $(document).ready(function () {

        //snackbar
        function snackbar($msg) {
            $('#snackbar').html($msg);
            $('#snackbar').toggleClass('show');
            setTimeout(function () {
                $('#snackbar').removeClass('show');
            }, 1600);
        }

        //send message
        $('#submit-form').click(function(e) {
            e.preventDefault();
            $("#messageModal").modal('hide');
            var body = $('#msgText').val();
            $('#msgText').val(' ');

            @auth
            $.ajax({
                url: '{{ route('messages.store') }}',
                method: "POST",
                data: {
                    '_token': '{{ csrf_token() }}',
                    'sender_id': {{ auth()->id() }},
                    'recipient_id': {{ $profile->user->id }},
                    'body': body,
                },
            }).done( function(data) {
                console.log("data: " + data);
                snackbar('Message Sent Successfully');
                loadMessages();

            });
            @else
            snackbar('Please log in first to send message');
            @endauth
        });
    });
</script>
    @endpush

resources/views/includes/dish_preview.blade.php
@foreach($dishes as $dish)
    <div class="col-lg-6 col-md-6">
        <!-- start .single-product -->
        <div class="product product--card">
            <div class="product__thumbnail">
                <div class="aspect_ratio"> <img src="{{ route('home') }}/storage/images/dish_images/{{ $dish->dish_thumbnail }}" alt="Product Image" class="ratio_img"> </div>
                <div class="prod_btn">
                    <a href="{{ route('dishes.show', ['id' => $dish]) }}" class="transparent btn--sm btn--round">MoreInfo</a>
                </div>
                <!-- end /.prod_btn -->
            </div>
            <!-- end /.product__thumbnail -->
            <div class="product-desc">
                <a href="{{ route('dishes.show', ['id' => $dish]) }}" class="product_title">
                    <h4> {{ $dish->dish_name }} </h4> </a>
                <ul class="titlebtm">
                    <li> <img class="auth-img" src="{{ route('home') }}/storage/images/profile_image/{{ $dish->profile->profile_image }}" alt="author image">
                        <p> <a href="{{ route('profile.show', ['profile' => $dish->profile->id]) }} #profile">{{ $dish->profile->user->name }}</a> </p>
                    </li>
                    <li class="product_cat a-color">
                            <span class="lnr lnr-map-marker"></span><span>{{ $dish->profile->city }},</span><span>{{ $dish->profile->area }}</span></li>
                </ul>
            </div>
            <!-- end /.product-desc -->
            <div class="product-purchase">
                <div class="price_love"> <span>৳{{ $dish->dish_price }}</span>

                    <div class="rating product--rating pull-right">
                        <ul>
                            @for ($i=1; $i <= 5; $i++)

                                <li>
                                    @if($i <= round($dish->avg_rating))
                                        <span class="fa fa-star"></span>
                                    @else
                                        <span class="fa fa-star-o"></span>
                                    @endif
                                </li>

                            @endfor
                        </ul>
                    </div>

                </div>

                <div class="sell">
                    <p>
                        <span data-toggle="tooltip" data-placement="bottom" title="Total Dish Sale">
                      <i class="fa fa-paper-plane-o" style="color:#f64646" aria-hidden="true"></i>
                      <span>{{ count($dish->completed_orders) }}</span></span>
                    </p>
                </div>
            </div>
            <!-- end /.product-purchase -->
        </div>
        <!-- end /.single-product -->
    </div>
@endforeach

resources/views/includes/dsp_order_status.blade.php
<div class="dsp-wrap">
    <div class="row">

        <div class="col-xs-12 col-md-12 text-xs-center">
            <a class="dsp-images" href="{{ route('profile.show', [ 'profile' => $dsp->user->profile->id]) }}"><img src="{{ route('home') }}/storage/images/profile_image/{{ $dsp->user->profile->profile_image }}"
                                                                                                                   alt="dsp profile"> </a>
            <div class="dsp-username">
                <h5>
                    <a href="{{ route('profile.show', [ 'profile' => $dsp->user->profile->id]) }}">{{ $dsp->user->name }}</a>
                </h5>

            </div>
        </div>
        <!--end:col -->
        <div class="col-xs-12 col-sm-12">
            <h5 class="dsp-title">{{ $dsp->service_title }}</h5>
            <p>
                <span class="bold">DSP-ID:</span>
                <span class="bold scolor">{{ $dsp->id }}</span>
            </p>
            <p>Service Hours: {{$dsp->service_hours_start}} to {{$dsp->service_hours_end}} </p>
            <p class="dsp-area">Service Area: <span>{{ $dsp->service_area }}</span></p>
        </div>


        </div>


        <div class="col-md-12">
            <div class="bottom-part">
                <div class="btm-part-2">
                    <div class="cost"><i class="fa fa-check"></i> Service charge:
                        ৳{{ $dsp->service_charge }}
                    </div>
                    <div class="mins"><i class="fa fa-motorcycle"></i> {{ $dsp->min_delivery_time }} hrs - {{ $dsp->max_delivery_time }} hrs
                    </div>

                </div>
            </div>
        </div>
        <!-- end:col -->
    </div>
    <!-- end:row -->
</div>
<!--end:Restaurant wrap -->

resources/views/includes/error_messeages.blade.php
@if ($errors->any())
  <div class="my-3">
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
          <li><span class="alert_icon lnr lnr-warning"></span>
            <strong>Oh snap! </strong>{{ $error }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span class="lnr lnr-cross" aria-hidden="true"></span>
            </button>
          </li>
        @endforeach
      </ul>

    </div>
  </div>
@endif

resources/views/includes/footer.blade.php
<footer class="footer-area">

    <div class="footer-big section--padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-12">
                    <div class="info-footer">
                        <div class="info__logo">
                            <img src="{{ route('home') }}/images/logo/full_logo.png" alt="footer logo">
                        </div>
                        <ul class="info-contact">
                            <li>
                                <span class="lnr lnr-envelope info-icon"></span>
                                <span class="info">info@khanidaani.com</span>
                            </li>
                            <li>
                                <span class="lnr lnr-map-marker info-icon"></span>
                                <span class="info">HQ: Sylhet, Bangladesh</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 col-md-12">
                    <div class="footer-menu">
                        <h5 class="footer-widget-title">Help and FAQs</h5>
                        <ul>
                            <li>
                                <a href="#">How to Join Us</a>
                            </li>
                            <li>
                                <a href="#">How It Work</a>
                            </li>
                            <li>
                                <a href="#">Buying and Selling</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="newsletter">
                        <div class="social social--color--filled">
                            <ul>
                                <li>
                                    <a href="#">
                                            <span class="fa fa-facebook"></span>
                                        </a>
                                </li>
                                <li>
                                    <a href="#">
                                            <span class="fa fa-twitter"></span>
                                        </a>
                                </li>

                                <li>
                                    <a href="#">
                                            <span class="fa fa-linkedin"></span>
                                        </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <a href="#" onclick="window.open('https://www.sitelock.com/verify.php?site=khanidaani.com','SiteLock','width=600,height=600,left=160,top=170');"><img title="1&1 SiteLock" src="https://shield.sitelock.com/shield/khanidaani.com" alt="Website security"></a>
                </div>
            </div>
        </div>
    </div>
    <div class="mini-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright-text">
                        <p>&copy; 2018
                            <a href="{{route('home')}}">KhaniDaani</a>. All rights reserved. Developed by <a href="">TeamJSN</a>
                        </p>
                    </div>
                    <div class="go_top">
                        <span class="lnr lnr-chevron-up"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/head.blade.php
<head>
    <meta charset="UTF-8">
    <!-- meta -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" CONTENT="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="XnHiwFWw5lh95jjA5gpzVOo7OBeNqJGj0j2tq1zl9CI" />
    <meta name="msvalidate.01" content="86407DD187368A5664666F9A1FA9D08D" />
    <title>KhaniDaani - @yield ('title') </title>
    <meta name="description" CONTENT="KhaniDaani is a freelance marketplace for chef & foodies. Here all housewives and potential cooks can earn bucks by selling their own food item.">
    <meta name="keywords" content="KhaniDaani, khanidaani, foods, freelancing, chef, women in freelancing">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/materialize-stepper.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/animate.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/fontello.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/jquery-ui.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/lnr-icon.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/owl.carousel.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/slick.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/trumbowyg.min.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/app.css">
    <link rel="stylesheet" href="{{ URL::to('/') }}/css/new.css">

    <script src="{{ URL::to('/') }}/js/vendor/jquery/jquery-1.12.3.js"></script>

    @stack('head-css')
    @stack('head-scripts')
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ URL::to('/') }}/images/logo/logo_icon.png">
</head>

resources/views/includes/injectjs.blade.php
<!-- inject:js -->
    @stack('scripts-footer-top')

    <script src="{{ URL::to('/') }}/js/vendor/jquery/popper.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery/uikit.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/bootstrap.min.js"></script>

    <script src="{{ URL::to('/') }}/js/vendor/grid.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery-ui.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery.barrating.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery.countdown.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery.counterup.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/jquery.easing1.3.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/owl.carousel.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/slick.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/tether.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/trumbowyg.min.js"></script>
    <script src="{{ URL::to('/') }}/js/vendor/waypoints.min.js"></script>
{{--<script src="{{ URL::to('/') }}/js/vendor/chart.bundle.min.js"></script>
    <script src="{{ URL::to('/') }}/js/dashboard.js"></script>--}}
    <script src="{{ asset('js/vendor/jquery.jscroll.js') }}"></script>
    <script src="{{ asset('js/vendor/moment-with-locales.min.js') }}"></script>
    <script src="{{ asset('js/vendor/moment-timezone.min.js') }}"></script>
    <script src="{{ asset('js/vendor/underscore-min.js') }}"></script>
    <script src="{{ asset('js/vendor/jQuery.maxlength.js') }}"></script>
    <script src="{{ URL::to('/') }}/js/main.js"></script>
    {{--<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyBeySPFGz7DIUTrReCRQT6HYaMM0ia0knA"></script>--}}
    {{--<script src="{{ URL::to('/') }}/js/map.js"></script>--}}
    <script src="{{ route('home') }}/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script src="{{ URL::to('/') }}/js/app.js" type="text/javascript"></script>

    @stack('scripts-footer-bottom')
    @stack('scripts-footer-bottom-2')

<!-- endinject -->

resources/views/includes/menu-dashboard.blade.php
<div class="dashboard_menu_area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="dashboard_menu">
                    <li class="{{ request()->is(route('profile.show', ['profile' => auth()->id()])) ? 'active' : '' }}">
                        <a href="{{ route('profile.show', ['profile' => auth()->id()]) }}">
                                    <span class="lnr lnr-home"></span>Profile</a>
                    </li>
                    <li class="{{ request()->is(route('profile.edit', ['profile' => auth()->id()])) ? 'active' : '' }}">
                        <a href="{{ route('profile.edit', ['profile' => auth()->id()]) }}">
                                    <span class="lnr lnr-cog"></span>Update</a>
                    </li>
                    <li>
                        <a href="{{ route('order.purchase') }}">
                                    <span class="lnr lnr-cart"></span>Orders</a>
                    </li>
                    <li>
                        <a href="{{ route('dishes.create') }}">
                            <span class="lnr lnr-file-add"></span>Add Dish</a>
                    </li>
                    <li class="{{ request()->is('profile_setting') ? 'active' : '' }}">
                        <a href="{{ route('dishes.manage') }}">
                                    <span class="lnr lnr-briefcase"></span>Manage Dish</a>
                    </li>
                    <li>
                        <a href="{{ route('profile.cashout') }}">
                                    <span class="lnr lnr-briefcase"></span>Payment</a>
                    </li>

                    <li>
                        <a href="{{ route('delivery.AddService') }}">
                            <span class="lnr lnr-file-add"></span>Add Delivery</a>
                    </li>

                    <li>
                        <a href="{{ route('pickerspoint.addpp') }}">
                            <span class="lnr lnr-file-add"> </span>Host Pick-up Point</a>
                    </li>
                </ul>
                <!-- end /.dashboard_menu -->
            </div>
            <!-- end /.col-md-12 -->
        </div>
        <!-- end /.row -->
    </div>
    <!-- end /.container -->
</div>

resources/views/includes/profile_sidebar.blade.php
<div class="col-lg-4 col-md-12">
    <aside class="sidebar sidebar_author" >
        @include( 'includes.author_info' )

       {{-- @if(auth()->id() == $profile->user_id)
            @if ($profile->user->isChef() or $profile->user->isDsp() or $profile->user->isPP())
        <div class="sidebar-card author-menu">
            <div class="row">
                        <div class="col-sm-12 col-md-5 text-center">
                            <h4 class="float-left scolor">Available:</h4></div>
                        <div class="col-md-7">
                            <form action="{{ route('profile.isAvailable', ['profile' => $profile->id]) }}" method="post">
                                @csrf
                                <label class="switch float-left mg-right">
                                    <input type="checkbox" name="is_available" onChange='this.form.submit();' value="1"
                                           @if($profile->is_available === 1)
                                           checked
                                            @endif
                                    >
                                    <span class="slider round"></span>
                                </label>
                                <h4 class="scolor"><b>
                                        @if($profile->is_available === 1)
                                            Yes
                                        @else
                                            No
                                        @endif
                                    </b></h4>
                            </form>
                </div>
                @endif

            </div>
        </div>@endif--}}

      {{--  <div class="freelance-status">
            <div class="author-badges">
                <div class="row">
                    <div class="col-sm-12 col-md-5 mg-bt text-center">@if(auth()->id() == $profile->user_id)
                            @if ($profile->user->isChef() or $profile->user->isDsp() or $profile->user->isPP())
                                <h4 class="float-left scolor">Available:</h4></div>
                    <div class="col-md-7"> <label class="switch float-left"> --}}{{--New css, last part, no js(w3school)--}}{{--
                            <input type="checkbox" checked>
                            <span class="slider round"></span>
                        </label> <h4 class="scolor"><b>Yes</b></h4></div>
                    @endif
                    @endif
                </div>

                <div class="author-btn"> <button class="btn btn--md btn--round" data-toggle="modal" data-target="#messageModal"
                                                 @if(auth()->id() == $profile->user_id)
                                                 aria-disabled="true" disabled="disabled"

                            @endif
                    >Message Chef</button> </div>
            </div>
        </div>--}}


        <div class="sidebar-card author-menu">
            <ul>
                <li> <a href="{{ route('profile.show', ['profile' => $profile->id]) }} #profile">User Profile</a> </li>
                <li> <a href="{{ route('profile.chefdishes', [ 'profile' => $profile->id]) }} #chefdish">Chef Dishes</a> </li>
                <li> <a href="{{ route('profile.chefdelivery', ['profile' => $profile->id]) }}">Delivery Services</a> </li>
                <li> <a href="{{ route('profile.pickerspoint', ['user' => $profile->user]) }} #chefpp">Pickers Point</a> </li>
            </ul>
        </div>
    </aside>

    <aside class="sidebar sidebar_author">
        <div class="sidebar-card message-card">
            <div class="card-title">
                <h4>Contact Chef</h4> </div>
            <div class="message-form">
                <form action="#">
                    <div class="form-group">
                        <textarea name="message" class="text_field" id="author-message" placeholder="Your message..."></textarea>
                    </div>
                    <div class="msg_submit">
                        <button type="submit" class="btn btn--md btn--round"  id="send_msg">send message</button>
                    </div>
                </form>
            </div>
            <!-- end /.message-form -->
        </div>
    </aside>
</div>

resources/views/includes/success_message.blade.php
@if(Session::has('success'))
  <div class="alert alert-success" role="alert">
    <span class="alert_icon lnr lnr-checkmark-circle"></span>
    <strong>Well done!</strong> {!! Session::get('success') !!}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span class="lnr lnr-cross" aria-hidden="true"></span>
    </button>
  </div>
@endif