routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/pickerspoint/addpp', 'PickersPointController@addpp')->name( 'pickerspoint.addpp');
Route::resource('pickerspoint', 'PickersPointController');


Route::get('/messages/compose', 'NotificationsController@compose')->name('messages.compose');

Route::get('/notifications/all', 'NotificationsController@notifications')->name('notifications.all');
Route::get('/notifications/mark_as_read', 'NotificationsController@mark_as_read')->name('notifications.mark_as_read');

Route::get('/', 'ViewController@index')->name('home');

Route::get('/profile/pickerspoint/{profile}', 'ProfileController@pickerspoint')->name('profile.pickerspoint');

Route::get('/profile/cashout', 'ProfileController@cashout')->name('profile.cashout');

Route::get('/profile/add_balance', 'ProfileController@add_balance')->name('profile.add_balance');

Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::get('/profile/create', 'ProfileController@create')->name('profile.create');

Route::post('/profile', 'ProfileController@store')->name( 'profile.store');

Route::get( '/profile/chefdishes/{profile}', 'ProfileController@chefdishes')->name('profile.chefdishes');

Route::post( '/profile/{profile}/isAvailable', 'ProfileController@isAvailable')->name('profile.isAvailable');

Route::get( '/profile/{user}/chefdelivery', 'ProfileController@chefdelivery')->name('profile.chefdelivery');

Route::get('/profile/{profile}', 'ProfileController@show')->name('profile.show');

Route::get('/profile/{profile}/edit', 'ProfileController@edit')->name('profile.edit');

Route::put( '/profile/{profile}', 'ProfileController@update')->name('profile.update');


Route::get( '/search/dsp', 'SearchController@dsp')->name( 'search.dsp');
Route::get( '/search/pp', 'SearchController@pp')->name( 'search.pp');

Route::get( '/search/livedish', 'SearchController@livedish')->name( 'search.livedish');
Route::post( '/search/livedish', 'SearchController@search_livedish')->name( 'search.livedish');


Route::get( '/delivery/AddService', 'DeliveryServiceController@create')->name( 'delivery.create');
Route::post( '/delivery/AddService', 'DeliveryServiceController@AddService')->name( 'delivery.AddService');

Auth::routes();

Route::get( '/dishes/manage', 'DishesController@manage')->name( 'dishes.manage');
Route::get( '/dishes/editdish', 'DishesController@editdish')->name( 'dishes.editdish');

Route::resource( '/dishes', 'DishesController');

Route::get('/ajax-subcat', 'RestApiController@jsonSubCat');
Route::get('/api/categories', 'RestApiController@jsonCategories');
Route::get('/ajax-areas', 'RestApiController@jsonAreas')->name('api.areas');
Route::get('/api/search-dish', 'RestApiController@jsonSearchDish')->name( 'api.search.dish');
Route::get('/api/search-dsp', 'RestApiController@jsonSearchDsp')->name( 'api.search.dsp');
Route::get('/api/search-pp', 'RestApiController@jsonSearchPP')->name( 'api.search.pp');
Route::get('/api/order/update', 'RestApiController@orderUpdate')->name( 'api.order.update');
Route::get('/api/order/load', 'RestApiController@orderLoad')->name( 'api.order.load');
Route::get('/api/dsp/getIDS', 'RestApiController@getIDs')->name( 'api.dsp.getIDs');

Route::get('/rating/{order}', 'RatingController@store')->name( 'rating.store');

Route::get('recover-pass', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('recover-pass');

Route::get('/home', 'HomeController@index');


// Auth Required Routes
Route::group(['middleware' => 'auth'], function (){
	// Order Routes
    Route::get( '/order/purchase', 'OrderController@purchase')->name( 'order.purchase');
    Route::get( '/order/selectdsp/{dish}', 'OrderController@selectdsp')->name( 'order.selectdsp');
    Route::get( '/order/confirm/{dsp}/{dish}', 'OrderController@confirm')->name( 'order.confirm');
    Route::get( '/order/confirm_pp/{pp}/{dish}', 'OrderController@confirm_pp')->name( 'order.confirm_pp');
    Route::get( '/order/store', 'OrderController@storeOrder')->name( 'order.store');
    Route::get( '/order/status/{order}', 'OrderController@status')->name( 'order.status');

	//Notifications
	Route::get('api/all_notifications', 'RestApiController@allNotification')->name( 'api.all_notifications');

	//Meassage
    Route::get('/messages/all', 'NotificationsController@messages')->name('messages.all');
    Route::get( '/messages/getMessages', 'MessageController@getMessages')->name( 'messages.getMessages');
	Route::get( '/messages/getAllMessages', 'MessageController@getAllMessages')->name( 'messages.getAllMessages');
	Route::get( '/messages/getSingleMessages', 'MessageController@getSingleMessages')->name( 'messages.getSingleMessages');
	Route::post( '/messages/store_with_auth', 'MessageController@store_with_auth')->name( 'messages.store_with_auth');
	Route::resource('messages', 'MessageController');

	// Payments
//    Route::post( 'admin/payment/add_balance', 'PaymentController@add_balance')->name( 'admin.payment.add_balance');
    Route::post( '/payment/add_balance', 'PaymentController@add_balance')->name( 'payment.add_balance');
    Route::post( '/payment/withdraw', 'PaymentController@withdraw')->name( 'payment.withdraw');

    //email to admin
    Route::post( '/order/complain', 'OrderController@complain')->name( 'order.complain');
});



Route::get('command/storage_link', function () {
    $exitCode = Artisan::call('storage:link');
    echo $exitCode;
    //
});

Route::get('command/migrate_fresh', function () {
    $exitCode = Artisan::call('migrate:fresh');
    echo $exitCode;
    //
});

Route::get('command/reset_order/{id}', function ($id) {
    $order = \App\Order::find($id);
    $order->chef_order_approved = 0;
    $order->chef_is_dish_ready = 0;
    $order->chef_is_dish_delivered = 0;
    $order->dsp_is_dish_recieved = 0;
    $order->dsp_is_dish_delivered = 0;
    $order->is_order_completed = 0;
    $order->status = 1;
    $order->created_at = \Carbon\Carbon::now();
    $order->save();

    return redirect()->back();

})->name('command.reset_order');

app/PickersPoint.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class PickersPoint extends Model
{
    //
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function profile() {
        return $this->belongsTo( Profile::class, 'user_id', 'user_id');
    }

    public function isBetweenTime()
    {
        $start = Carbon::parse($this->service_hours_start);
        $end = Carbon::parse($this->service_hours_end);

        $now = Carbon::now();

        if($start->lt($end)) {
            if($now->between($start, $end)) {
                return true;
            } else {
                return false;
            }
        }
        if($start->gt($end)) {
            if($now->gt($start) || ($now->lt($start) && $now->lt($end) ) ) {
                return true;
            }
        }
        return false;
    }

}

app/Http/Controllers/PickersPointController.php
<?php

namespace App\Http\Controllers;

use App\PickersPoint;
use Illuminate\Http\Request;

class PickersPointController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $validatedData = $request->validate([
            'name' => 'required|max:50',
            'type' => 'required|max:20',
            'open_at' => 'required',
            'close_at' => 'required',
            'charge' => 'required|integer|min:10|max:50',
            'address' => 'required|max:100',
            'address_hint' => 'required|max:50',
            'phone' => 'required',

        ]);

        $user = auth()->user();

        $pp = new PickersPoint;
        $pp->user_id = $user->id;
        $pp->name = $request->input('name');
        $pp->type = $request->input('type');
        $pp->open_at = $request->input('open_at');
        $pp->close_at = $request->input('close_at');
        $pp->charge = $request->input('charge');
        $pp->address = $request->input('address');
        $pp->address_hint = $request->input('address_hint');
        $pp->phone = $request->input('phone');

        $pp->save();



        return redirect()->route('profile.pickerspoint', ['profile' => $user->id])->with('success', 'New PickersPoint is Created Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PickersPoint  $pickersPoint
     * @return \Illuminate\Http\Response
     */
    public function show(PickersPoint $pickersPoint)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PickersPoint  $pickersPoint
     * @return \Illuminate\Http\Response
     */
    public function edit(PickersPoint $pickersPoint)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PickersPoint  $pickersPoint
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PickersPoint $pickersPoint)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PickersPoint  $pickersPoint
     * @return \Illuminate\Http\Response
     */
    public function destroy(PickersPoint $pickersPoint)
    {
        //
    }

    public function addpp() {
        $user = auth()->user();
        if(!$user->profile->address || !$user->profile->mobile_no || !$user->profile->city) {
            return redirect()->route('profile.edit', ['profile' => $user->profile->id])->withErrors('You Must Fill Up The Profile Information To Create a New Dish');
        }
        
        $profile = auth()->user()->profile;
        return view('pickerspoint.addpp', compact('profile'));
    }
}

resources/views/pickerspoint/addpp.blade.php
@extends ('layouts.master') @section ('title', 'Add Pickers Point') @section ('content')

    <!--================================
        START BREADCRUMB AREA
    =================================-->
    <section class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="page-title">Add pick up point</h1>
                    <p class="text-white">Note: All of the field are mandatory</p>
                </div>
                <!-- end /.col-md-12 -->
            </div>
            <!-- end /.row -->
        </div>
        <!-- end /.container -->
    </section>
    <!--================================
                END BREADCRUMB AREA
            =================================-->

    <!--================================
                    START DASHBOARD AREA
            =================================-->
    <section class="dashboard-area">
        @include( 'includes.menu-dashboard' )


        <div class="dashboard_contents">
            <div class="container">
                @include('includes.error_messeages')
                @include('includes.success_message')
                <div class="row">
                    <div class="col-lg-8 col-md-7">
                        <form action="{{ route('pickerspoint.store') }}" method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="upload_modules">
                                <div class="modules__title">
                                    <h3>Add Pick Up Point Detail</h3>
                                </div>
                                <!-- end /.module_title -->
                                <div class="modules__content">

                                    <div class="form-group max-length">
                                        <label for="shop_name">Shop Name
                                            <span> (Max 50 characters) </span>
                                        </label>
                                        <input name="name" type="text" id="shop_name" class="text_field"
                                               placeholder="Enter your Shop name here..." maxlength = "50" required>

                                    </div>
                                    <div class="form-group max-length">
                                        <label for="shop_type">Shop Type
                                            <span> (eg. Departmental Store )</span>
                                        </label>
                                        <input name="type" type="text" id="shop_type" class="text_field"
                                               placeholder="Enter your Shop Type here..."  maxlength = "20" required>
                                    </div>

                                    {{-- <div class="form-group no-margin">
                                         <label for="product_name">Service Description
                                             <span>(Describe Everything in detail)</span>
                                         </label>
                                         <textarea name="service_description" rows="10" class="form-control"
                                                   placeholder="max 1000 character" id="article-ckeditor"></textarea>
                                     </div>--}}
                                </div>

                            </div>

                            <div class="upload_modules with--addons">
                                <div class="modules__title">
                                    <h3>Open Hours & Charge</h3>
                                </div>
                                <!-- end /.module_title -->

                                <div class="modules__content">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <label for="sh_start">Open Time</label>
                                                    <input type="time" name="open_at" id="sh_start"
                                                           class="text_field"
                                                           placeholder="Start Time" required>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end /.col-md-6 -->

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <label for="sh_close">Close Time</label>
                                                    <input type="time" id="sh_close" class="text_field"
                                                           placeholder="End Time" name="close_at" required>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end /.col-md-6 -->

                                    </div>
                                    <!-- end /.row -->

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="service_charge">Service Charge <span>(Within 10-50 taka)</span>
                                                </label>
                                                {{--<input name="charge" type="number" id="service_charge" class="text_field"
                                                       placeholder="10-50" min="10" max="50" required>--}}
                                                <select name="charge" id="service_charge" class="form-control">
                                                    <option value="10">10</option>
                                                    <option value="15">15</option>
                                                    <option value="20">20</option>
                                                    <option value="25">25</option>
                                                    <option value="30">30</option>
                                                    <option value="35">35</option>
                                                    <option value="40">40</option>
                                                    <option value="45">45</option>
                                                    <option value="50">50</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end /.modules__content -->
                            </div>

                            <div class="upload_modules">
                                <a class="toggle_title" href="#collapse2" role="button" data-toggle="collapse"
                                   aria-expanded="false" aria-controls="collapse2">
                                    <h4>Contacts
                                        <span class="lnr lnr-chevron-down"></span>
                                    </h4>
                                </a>

                                <div class="information__set toggle_module collapse show" id="collapse2">
                                    <div class="modules__content">

                                        <div class="form-group max-length">
                                            <label for="full_address">Full Address</label>
                                            <div class="input-group">
                                                <textarea name="address" id="full_address"
                                                       class="text_field"
                                                          placeholder="Holding NO:1098,Main Road-1, Block-E, Shahjalal Uposhohor, Sylhet."  maxlength = "100" required>{{ $profile->address }}</textarea>
                                            </div>
                                        </div>

                                        <div class="form-group max-length">
                                            <label for="address_hint">Address Hint (Optional)</label>
                                            <div class="input-group">
                                                <input name="address_hint" type="text" id="address_hint"
                                                       class="text_field" placeholder="Near Brack Bank"  maxlength = "50" required value="{{ $profile->address_hint }}">
                                            </div>
                                        </div>

                                        <div class="form-group max-length">
                                            <label for="phone_number">Phone No</label>
                                            <div class="input-group">
                                                <input name="phone" type="tel" id="phone_number"
                                                       class="text_field" placeholder="01711966966"  maxlength = "11" required value="{{ $profile->mobile_no }}">
                                            </div>
                                        </div>

                                    </div>
                                    <!-- end /.modules__content -->
                                </div>
                            </div>
                            <!-- end /.upload_modules -->


                            <button type="submit" class="btn btn--round btn--fullwidth btn--lg">Submit
                            </button>
                        </form>
                    </div>
                    <!-- end /.col-md-8 -->

                    <div class="col-lg-4 col-md-5">
                        <aside class="sidebar upload_sidebar s-hide">
                            <div class="sidebar-card">
                                <div class="card-title">
                                    <h3>Detail Help</h3>
                                </div>

                                <div class="card_content">
                                    <div class="card_info">
                                        <h4>Name & Description</h4>
                                        <p>Add your service name, also use common name so it's can found easily from search. Also, add detail info about the services</p>
                                    </div>

                                    <div class="card_info">
                                        <h4>Service Area</h4>
                                        <p>Define your area of services so chef can know that if your good for his/her dishes.</p>
                                    </div>

                                    <div class="card_info">
                                        <h4>Service Hours</h4>
                                        <p>When you can work for the deliver? If your professional deliverer select your office time</p>
                                        <p>If your a freelance deliverer add your available time.</p>
                                    </div>
                                </div>
                            </div>
                            <!-- end /.sidebar-card -->

                            <div class="sidebar-card">
                                <div class="card-title">
                                    <h3>Price & Delivery time</h3>
                                </div>

                                <div class="card_content">
                                    <p>Note: You will have to deliver the dish before it's maximum time.</p>
                                    <ul>
                                        <li>Servcie Charge: For how much you will deliver the dish to your defined service area</li>
                                        <li>Min Delivery Time: Minimum time of the deliver</li>
                                        <li>Max Delivery Time: Maximum time of the delivery</li>
                                    </ul>

                                </div>
                            </div>
                            <!-- end /.sidebar-card -->
                        </aside>

                    </div>
                    <!-- end /.col-md-4 -->
                </div>
                <!-- end /.row -->
            </div>
            <!-- end /.container -->
        </div>
        <!-- end /.dashboard_menu_area -->
    </section>
    <!--================================
                    END DASHBOARD AREA
            =================================-->

@endsection

resources/views/pickerspoint/pp_preview.blade.php
<!-- Pikers Point Start -->


    <div class="row">
        <div class="col-sm-12">
            <a class="strip_list grid" href="#">
                <div class="desc">
                    <div class="thumb_strip">
                        <img src="{{ route('home') }}/storage/images/profile_image/{{ $pp->user->profile->profile_image }}" alt="User Image">
                    </div>

                    <h3 class="pp_title">{{ $pp->name }}</h3>
                    <div class="type">
                        {{ $pp->type }}
                    </div>
                    <div class="location">
                        {{ $pp->address }} <br>
                    </div>
                    <div class="hours">
                        {{--<span class="opening">Opens @ {{ date('h:i A', strtotime($pp->open_at) ) }}.</span><span class="closing"> Close @ {{ \Carbon\Carbon::parse($pp->close_at)->format('h:m A') }}</span>--}}
                        <span class="opening">Opens @ {{ date('h:i A', strtotime($pp->open_at) ) }}.</span><span class="closing"> Closes @ {{ date('h:i A', strtotime($pp->close_at) ) }}</span>
                    </div>
                    <br>

                    <div class="product-purchase">
                        <h4 class="float-left mg-bt">Pick-up Point id: <b class="scolor">{{ $pp->id }}</b></h4>
                        <div class="price_love"><span data-toggle="tooltip" data-placement="button" title="Service charge">৳{{ $pp->charge }}</span>
                        </div>
                        {{--<div class="rating product--rating pull-right">
                            <ul>
                                <li><span class="fa fa-star-o"></span></li>
                                <li><span class="fa fa-star-o"></span></li>
                                <li><span class="fa fa-star-o"></span></li>
                                <li><span class="fa fa-star-o"></span></li>
                                <li><span class="fa fa-star-o"></span></li>
                            </ul>
                        </div>--}}
                    </div>

                </div>
            </a>
        </div>
    </div><!-- End strip_list-->
<!-- Pikers Point End -->

resources/views/pickerspoint/pp_preview_template.blade.php
<script type="text/template" class="template" id="pp_template">

    <div class="col-md-6 single-dsp">

        <a class="strip_list grid" href="#">
            <div class="desc">
                <div class="thumb_strip">
                    <img src="{{ route('home') }}/storage/images/profile_image/<%- pp.profile.profile_image %>"
                         alt="pp profile">
                </div>

                <h3 class="pp_title"><%- pp.name %></h3>
                <div class="type">
                    <%- pp.type %>
                </div>
                <div class="location">
                    <%- pp.address %> <br>
                </div>
                <div class="hours mg-bt">
                    {{--<span class="opening">Opens @ {{ date('h:i A', strtotime($pp->open_at) ) }}.</span><span class="closing"> Close @ {{ \Carbon\Carbon::parse($pp->close_at)->format('h:m A') }}</span>--}}
                    <span class="opening">Opens @ <%- moment(pp.open_at, "HH:mm:ss").format("hh:mm A") %></span>
                    <span class="closing"> Close @ <%- moment(pp.close_at, "HH:mm:ss").format("hh:mm A") %></span>
                </div>
                <div>


                </div>
                <div class="product-purchase">
                    <h4 class="float-left">Pick-up Point id:<b class="scolor"> <%- pp.id %></b></h4>
                    <div class="price_love"><span data-toggle="tooltip" data-placement="button" title="Service charge">৳<%- pp.charge %></span>
                    </div>
                    {{--<div class="rating product--rating pull-right">
                        <ul>
                            <li><span class="fa fa-star-o"></span></li>
                            <li><span class="fa fa-star-o"></span></li>
                            <li><span class="fa fa-star-o"></span></li>
                            <li><span class="fa fa-star-o"></span></li>
                            <li><span class="fa fa-star-o"></span></li>
                        </ul>
                    </div>--}}
                </div>

            </div>
        </a>
        <!--end:Restaurant wrap -->

    </div>


</script>